AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tesseract OCR Sample with AWS Lambda Container Images using AWS SAM
Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'ccm-sam-lambda-dev'
      MemorySize: 512
      PackageType: Image
      Timeout: 900
      Policies:
        - AmazonS3FullAccess
    Metadata:
      DockerTag: latest
      DockerContext: ./src/
      Dockerfile: Dockerfile
